[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "algometa"
version = "0.0.1"
dependencies = ["typer", "numpy"]
optional-dependencies = { dev = [
    "pandas",
    "matplotlib",
    "seaborn",
    "plotly",
    "scipy",
    "statsmodels",
] }
